spring:
  datasource:
    url: jdbc:mysql://localhost/algafood_test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Rte@1207
    hikari:
      maximum-pool-size: 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:db/migration
    enabled: true