spring:
  datasource:
    url: jdbc:mysql://localhost/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: admin
    password: Rte@1207
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true